---
event_type: PushEvent
avatar: "https://avatars.githubusercontent.com/u/194764?"
user: haampie
date: 2024-05-11
repo_name: spack/spack
html_url: https://github.com/spack/spack/commit/55f37dffe52d60c19522bca2ff79a2d5ed6632a1
repo_url: https://github.com/spack/spack
---

<a href='https://github.com/haampie' target='_blank'>haampie</a> pushed to <a href='https://github.com/spack/spack' target='_blank'>spack/spack</a>

<small>oci: improve default_retry (#44132)

Apparently urllib can throw a range of different exceptions:

1. HTTPError
2. URLError with e.reason set to the actual exception
3. TimeoutError from getresponse, which is not wrapped</small>

<a href='https://github.com/spack/spack/commit/55f37dffe52d60c19522bca2ff79a2d5ed6632a1' target='_blank'>View Commit</a>