---
event_type: IssuesEvent
avatar: "https://avatars.githubusercontent.com/u/37929162?"
user: mergify[bot]
date: 2024-04-10
repo_name: flux-framework/flux-core
html_url: https://github.com/flux-framework/flux-core/issues/5862
repo_url: https://github.com/flux-framework/flux-core
---

<a href='https://github.com/mergify[bot]' target='_blank'>mergify[bot]</a> closed issue <a href='https://github.com/flux-framework/flux-core/issues/5862' target='_blank'>flux-framework/flux-core#5862</a>.

<p>Missing test_must_fail function in Flux testing environment</p><small>Within `flux-core/t/t3203-instance-recovery.t` file, `flux start --recovery=$(pwd)/test2` command is succeeding even though the `content.sqlite` file is set to read-only (chmod 400)....</small><a href='https://github.com/flux-framework/flux-core/issues/5862' target='_blank'>View Comment</a>